### ISSUE TITLE
recipes api endpoint?

### ISSUE THREAD

**Issue by idkjs** [tobiastimm/reason-react-hooks-example#5]
Hi @tobiastimm,

Thanks for sharing this.

Can you share the endpoint you were using for graphql?

Also, your talk link is dead.

Peace to you.

**Comment by tobiastimm** [comment]
@idkjs 
https://api-euwest.graphcms.com/v1/cjvtuzuav5tux01etrbx95u65/master
This is the API endpoint.
Regarding the talk, I will update the slides within the next weeks, so unfortunately, you need to wait.
